# Site settings
baseURL = "https://hopyardfarm.org"
languageCode = "en-US"
title = "Hopyard Farm"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# for Github deployment
caches]
  [caches.images]
    dir = ':cacheDir/images'

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Hopyard Farm LLC, Graton CA<br>"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "Douglas Eck"
  description = "Hopyard Farm is located in Graton, California."
  shareImage = "images/social.jpg"
  twitterHandle = "douglaseck"

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    #[params.visual.video]
    #  enable = false
    #  mute = true
    #  file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"
      [[params.links.list1.link]]
        text = "Email"
        url = 'mailto:amie@hopyardfarm.org'
        new_tab = true # Default, open at same tab

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://instagram.com/hopyard_farm"
        new_tab = true # Default, open at same tab
	
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
